[package]
name = "my_lambda_function"
version = "0.1.0"
authors = ["RyanJarv <ryan_gerstenkorn@fastmail.fm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
